### ISSUE TITLE
Publish this to pub.dartlang.org?

### ISSUE THREAD

**Issue by thosakwe** [dart-atom/atom.dart#49]

**Comment by devoncarew** [comment]
We don't have the bandwidth to publish ourselves - that would like imply a bit more of a SLA than we can muster. Contributions here are welcome however :)

**Comment by thosakwe** [comment]
Wait, not sure if I read that right. Can you explain?

**Comment by devoncarew** [comment]
A git repo for a package is a bit less discoverable than a published one. In my mind, publishing a package implies a bit higher level of a SLA (a higher level of support, maintenance, pushing patches and new releases, ...). This package was primarily for our own use, and we didn't have the bandwidth to support it generally.

**Comment by thosakwe** [comment]
Ah, I understand now. Thanks for the clarification.
